/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    makes: Make;
    optionals: Optional;
    locations: Location;
    vehicles: Vehicle;
    leads: Lead;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    makes: MakesSelect<false> | MakesSelect<true>;
    optionals: OptionalsSelect<false> | OptionalsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    financeSettings: FinanceSetting;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    financeSettings: FinanceSettingsSelect<false> | FinanceSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Account che possono accedere all'admin del sito.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admin: accesso completo. Editor: gestisce veicoli, pagine, lead.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Immagini e media usati nel sito (auto, banner, loghi).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descrivi brevemente l'immagine. Obbligatorio per accessibilità e SEO.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Marche dei veicoli. Pre-popolate al primo avvio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makes".
 */
export interface Make {
  id: number;
  name: string;
  /**
   * Generato automaticamente dal nome. Modificabile.
   */
  slug: string;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lista degli optional disponibili. Pre-popolata al primo avvio, espandibile.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "optionals".
 */
export interface Optional {
  id: number;
  name: string;
  category: 'comfort' | 'sicurezza' | 'multimedia' | 'esterni' | 'interni' | 'assistenza-guida';
  updatedAt: string;
  createdAt: string;
}
/**
 * Le sedi del concessionario (showroom, officine, ecc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  address: string;
  zip: string;
  city: string;
  province: string;
  phone?: string | null;
  /**
   * Numero E.164, es. +393331234567
   */
  whatsapp?: string | null;
  email?: string | null;
  openingHours?:
    | {
        /**
         * Es. "Lun–Ven" o "Sab"
         */
        days: string;
        /**
         * Es. "9:00–13:00, 15:00–19:00"
         */
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Posizione sulla mappa.
   *
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stock dei veicoli in vendita.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  /**
   * Generato automaticamente da Marca + Modello + Allestimento. Modificabile.
   */
  title: string;
  /**
   * URL della pagina veicolo. Generato dal titolo, modificabile.
   */
  slug: string;
  /**
   * Codice interno per riferimento gestionale (opzionale).
   */
  internalCode?: string | null;
  availability: 'available' | 'reserved' | 'sold' | 'incoming';
  /**
   * Mostra il veicolo nella sezione "In evidenza" della homepage.
   */
  featured?: boolean | null;
  make: number | Make;
  model: string;
  /**
   * Es. "320d xDrive Msport"
   */
  trim?: string | null;
  condition: 'nuovo' | 'km0' | 'aziendale' | 'usato';
  /**
   * Mese e anno di prima immatricolazione.
   */
  firstRegistration: string;
  /**
   * In km.
   */
  mileage: number;
  fuel: 'benzina' | 'diesel' | 'gpl' | 'metano' | 'ibrida' | 'ibrida-plug-in' | 'elettrica';
  transmission: 'manuale' | 'automatico' | 'semiautomatico';
  drivetrain?: ('anteriore' | 'posteriore' | 'integrale') | null;
  /**
   * Nascosto per veicoli elettrici.
   */
  displacement?: number | null;
  powerKw: number;
  /**
   * Calcolato automaticamente da kW (× 1,36). Sovrascrivibile.
   */
  powerCv?: number | null;
  co2?: number | null;
  euroClass?: ('euro-4' | 'euro-5' | 'euro-6' | 'euro-6d' | 'euro-6e') | null;
  doors?: number | null;
  seats?: number | null;
  bodyType?:
    | ('berlina' | 'station-wagon' | 'suv' | 'crossover' | 'coupe' | 'cabrio' | 'monovolume' | 'city-car' | 'pick-up')
    | null;
  exteriorColor?: string | null;
  exteriorColorType?: ('metallizzato' | 'pastello' | 'perlato' | 'opaco') | null;
  interiorColor?: string | null;
  interiorMaterial?: ('tessuto' | 'pelle' | 'pelle-tessuto' | 'alcantara' | 'pelle-alcantara') | null;
  price: number;
  /**
   * Compila per mostrare un'offerta con prezzo precedente barrato.
   */
  priceStrikethrough?: number | null;
  /**
   * Spunta se l'IVA è esposta e detraibile.
   */
  vatDeductible?: boolean | null;
  /**
   * Rata mensile indicativa mostrata in pagina veicolo. I parametri di default vivono in Configurazione → Finanziamento.
   */
  financingMonthly?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Massimo 6 punti da mostrare nel riepilogo (es. "Tagliandi ufficiali", "Garanzia 24 mesi").
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  optionals?: (number | Optional)[] | null;
  /**
   * Trascina per riordinare. La prima foto è la copertina. Almeno 1 foto.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Link a video promozionale (opzionale). Solo URL pubblici.
   */
  videoUrl?: string | null;
  /**
   * Dove si trova fisicamente il veicolo. Default: prima sede se ne esiste una sola.
   */
  location?: (number | null) | Location;
  /**
   * Fallback: titolo del veicolo.
   */
  metaTitle?: string | null;
  /**
   * Lunghezza ottimale 140–160 caratteri.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Richieste informazioni, prenotazioni test drive, valutazioni dell'usato.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  type: 'info' | 'test-drive' | 'valutazione' | 'finanziamento';
  status: 'nuovo' | 'contattato' | 'chiuso';
  message?: string | null;
  /**
   * Veicolo a cui si riferisce la richiesta (se applicabile).
   */
  vehicle?: (number | null) | Vehicle;
  /**
   * Fotografia del veicolo al momento della richiesta. Utile se il veicolo viene rimosso.
   */
  vehicleSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Visibili solo allo staff.
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Pagina di origine della richiesta.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pagine statiche del sito (Chi siamo, Servizi, Contatti, ecc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL della pagina (es. "chi-siamo"). Generato dal titolo, modificabile.
   */
  slug: string;
  /**
   * Componi la pagina trascinando i blocchi nell'ordine voluto.
   */
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            cta?:
              | {
                  label: string;
                  href: string;
                  variant?: ('primary' | 'secondary') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            align?: ('left' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGrid';
          }
        | {
            heading: string;
            description?: string | null;
            buttonLabel: string;
            buttonHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  author: string;
                  role?: string | null;
                  quote: string;
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
      )[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'makes';
        value: number | Make;
      } | null)
    | ({
        relationTo: 'optionals';
        value: number | Optional;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makes_select".
 */
export interface MakesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "optionals_select".
 */
export interface OptionalsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  zip?: T;
  city?: T;
  province?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  openingHours?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  coordinates?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  internalCode?: T;
  availability?: T;
  featured?: T;
  make?: T;
  model?: T;
  trim?: T;
  condition?: T;
  firstRegistration?: T;
  mileage?: T;
  fuel?: T;
  transmission?: T;
  drivetrain?: T;
  displacement?: T;
  powerKw?: T;
  powerCv?: T;
  co2?: T;
  euroClass?: T;
  doors?: T;
  seats?: T;
  bodyType?: T;
  exteriorColor?: T;
  exteriorColorType?: T;
  interiorColor?: T;
  interiorMaterial?: T;
  price?: T;
  priceStrikethrough?: T;
  vatDeductible?: T;
  financingMonthly?: T;
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  optionals?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  videoUrl?: T;
  location?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  type?: T;
  status?: T;
  message?: T;
  vehicle?: T;
  vehicleSnapshot?: T;
  notes?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              heading?: T;
              body?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        imageGrid?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    author?: T;
                    role?: T;
                    quote?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identità del sito: nome, logo, colori, social, dati legali, footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  colorPrimary?: string | null;
  colorAccent?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'tiktok' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  companyName?: string | null;
  vat?: string | null;
  rea?: string | null;
  footerText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Parametri di default per il calcolatore rata. Modificarli aggiorna tutte le pagine veicolo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financeSettings".
 */
export interface FinanceSetting {
  id: number;
  defaultTan: number;
  defaultTaeg: number;
  defaultDownPaymentPercent: number;
  defaultMonths: number;
  availableMonths?:
    | {
        months: number;
        id?: string | null;
      }[]
    | null;
  disclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  colorPrimary?: T;
  colorAccent?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  companyName?: T;
  vat?: T;
  rea?: T;
  footerText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financeSettings_select".
 */
export interface FinanceSettingsSelect<T extends boolean = true> {
  defaultTan?: T;
  defaultTaeg?: T;
  defaultDownPaymentPercent?: T;
  defaultMonths?: T;
  availableMonths?:
    | T
    | {
        months?: T;
        id?: T;
      };
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}